version: '3.8'
services:
  notes:
    build:
      context: .
    environment:
      - .env
    image: ${IMAGE_NAME}
    container_name: ${SERVICE_NAME}
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/docs
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: marcus-yh/python:latest
    container_name: python
    volumes:
      - ${PWD}:/docs
